-- CreateTable
CREATE TABLE `Properties` (
    `id` VARCHAR(191) NOT NULL,
    `externalId` VARCHAR(191) NOT NULL,
    `status` VARCHAR(191) NOT NULL,
    `verifiedAt` DATETIME(3) NULL,
    `verifiedBy` VARCHAR(191) NULL,
    `sourceUrl` TEXT NULL,
    `title` VARCHAR(255) NOT NULL,
    `category` VARCHAR(191) NOT NULL,
    `price` DECIMAL(14, 2) NOT NULL,
    `rentMonths` INTEGER NULL,
    `description` LONGTEXT NULL,
    `houseType` VARCHAR(191) NULL,
    `commercialType` VARCHAR(191) NULL,
    `landType` VARCHAR(191) NULL,
    `bedrooms` INTEGER NULL,
    `bathrooms` INTEGER NULL,
    `ensuiteCount` INTEGER NULL,
    `sizeValue` DECIMAL(12, 2) NULL,
    `sizeUnit` ENUM('sqm', 'acre', 'plot', 'metre', 'feet') NULL,
    `sizeWidth` DECIMAL(10, 2) NULL,
    `sizeLength` DECIMAL(10, 2) NULL,
    `features` JSON NULL,
    `featuresOther` TEXT NULL,
    `locationRegion` VARCHAR(191) NOT NULL,
    `locationDistrict` VARCHAR(191) NOT NULL,
    `locationWard` VARCHAR(191) NULL,
    `locationStreet` VARCHAR(191) NULL,
    `locationGpsLat` DECIMAL(9, 6) NULL,
    `locationGpsLng` DECIMAL(9, 6) NULL,
    `ownerFullName` VARCHAR(191) NULL,
    `ownerPhone` VARCHAR(30) NULL,
    `ownerAltPhone` VARCHAR(30) NULL,
    `ownerEmail` VARCHAR(255) NULL,
    `ownerNationalId` VARCHAR(50) NULL,
    `brokerFullName` VARCHAR(191) NULL,
    `brokerPhone` VARCHAR(30) NULL,
    `brokerAltPhone` VARCHAR(30) NULL,
    `brokerEmail` VARCHAR(255) NULL,
    `brokerNatReg` VARCHAR(191) NULL,
    `brokerNatDist` VARCHAR(191) NULL,
    `images` JSON NULL,
    `videos` JSON NULL,
    `listingKind` ENUM('single', 'project', 'unit') NOT NULL DEFAULT 'single',
    `parentExternalId` VARCHAR(191) NULL,
    `unitLabel` VARCHAR(50) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `Properties_externalId_key`(`externalId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
